version: "3.9"

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - php-fpm-socket:/var/run
        links:
            - php-fpm
    app:
        image: php:8-fpm
        volumes:
            - ./src:/var/www/html
            - ./docker/php/zzz-www.conf:/usr/local/etc/php-fpm.d/zzz-www.conf
            - php-fpm-socket:/var/run

volumes:
    php-fpm-socket:
