version: "3.9"

services:
    nginx:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        ports:
            - "8080:8080"
            - "8081:8081"
        volumes:
            - php-fpm-socket:/var/run/php-fpm
        depends_on:
            - php-fpm
    php-fpm:
        build:
            context: ./docker/php-fpm/
            dockerfile: Dockerfile
        volumes:
            - php-fpm-socket:/var/run/php-fpm
            - ./src:/var/www/html

volumes:
    php-fpm-socket:
