version: "3.9"

services:
    web:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        ports:
            - "8080:8080"
        volumes:
            - php-fpm-socket:/var/run/php-fpm
            - ./src:/var/www/html
            #- ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php-fpm
    app:
        stdin_open: true
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        volumes:
            - php-fpm-socket:/var/run/php-fpm
            - ./src:/var/www/html

volumes:
    php-fpm-socket:
