version: "3.9"

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - php-fpm-socket:/var/run
        depends_on:
            - php-fpm
    app:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        volumes:
            - ./src:/var/www/html
            - php-fpm-socket:/var/run

volumes:
    php-fpm-socket:
